version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: chattrix-postgres-container
    restart: always
    environment:
      POSTGRES_USER: elinor
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chattrix
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
